name: bintray

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-deb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Build deb package
      run: cargo deb --verbose --deb-version "${{ steps.extract_version.outputs.version }}+${{ steps.extract_time.outputs.time }}"

    - name: Get deb filename
      shell: bash
      run: echo "##[set-output name=debfile;]$(basename ./target/debian/*.deb)"
      id: extract_debfile
    - name: Get package version
      shell: bash
      run: echo "##[set-output name=version;]$(awk -F'=' '/version/ {print $2}' Cargo.toml | sed 's/\"//g;s/ //g')"
      id: extract_version
    - name: Get time of day
      shell: bash
      run: echo "##[set-output name=time;]$(date +%s)"
      id: extract_time

    - name: Upload deb package to Bintray
      uses: bpicode/github-action-upload-bintray@master
      with:
        file: ./target/debian/${{ steps.extract_debfile.outputs.debfile }}
        api_user: cmars232
        api_key: ${{ secrets.BINTRAY_API_KEY }} # An API key can be obtained from the user profile page.
        #gpg_passphrase: ${{ secrets.BINTRAY_GPG_PASSPHRASE }} # Optional, for this to work Bintray requires a GPG public/private keypair configured for the repository owner (individual or organization).
        repository_user: cmars232
        repository: deb
        package: libnss-wiregarden
        version: ${{ steps.extract_version.outputs.version }}+${{ steps.extract_time.outputs.time }}
        upload_path: pool/m/main # Typical for debian repository layout
        publish: 1
        calculate_metadata: true # Schedule metadata calculation after upload
        deb_distribution: focal
        deb_component: main
        deb_architecture: amd64
